[2023-03-29T18:51:51.545+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available __airflow_temporary_run_2023-03-29T18:51:48.922573+00:00__ [queued]>
[2023-03-29T18:51:51.552+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available __airflow_temporary_run_2023-03-29T18:51:48.922573+00:00__ [queued]>
[2023-03-29T18:51:51.553+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T18:51:51.554+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-03-29T18:51:51.555+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T18:51:51.562+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2022-01-01 00:00:00+00:00
[2023-03-29T18:51:51.568+0000] {standard_task_runner.py:55} INFO - Started process 17678 to run task
[2023-03-29T18:51:51.571+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', '__***_temporary_run_2023-03-29T18:51:48.922573+00:00__', '--job-id', '18', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmp92t66q9h']
[2023-03-29T18:51:51.574+0000] {standard_task_runner.py:83} INFO - Job 18: Subtask is_api_available
[2023-03-29T18:51:51.618+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available __airflow_temporary_run_2023-03-29T18:51:48.922573+00:00__ [running]> on host 9dcb783b1f3a
[2023-03-29T18:51:51.656+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2022-01-01T00:00:00+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=__***_temporary_run_2023-03-29T18:51:48.922573+00:00__
[2023-03-29T18:51:51.658+0000] {http.py:120} INFO - Poking: api/
[2023-03-29T18:51:51.665+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2023-03-29T18:51:51.668+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2023-03-29T18:51:51.882+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2023-03-29T18:51:51.894+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20220101T000000, start_date=20230329T185151, end_date=20230329T185151
[2023-03-29T18:51:51.924+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-03-29T18:51:51.948+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
