[2023-03-29T18:44:03.115+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2023-03-29T18:44:00.987028+00:00 [queued]>
[2023-03-29T18:44:03.120+0000] {taskinstance.py:1165} INFO - Dependencies all met for <TaskInstance: user_processing.is_api_available manual__2023-03-29T18:44:00.987028+00:00 [queued]>
[2023-03-29T18:44:03.121+0000] {taskinstance.py:1362} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T18:44:03.122+0000] {taskinstance.py:1363} INFO - Starting attempt 1 of 1
[2023-03-29T18:44:03.124+0000] {taskinstance.py:1364} INFO - 
--------------------------------------------------------------------------------
[2023-03-29T18:44:03.131+0000] {taskinstance.py:1383} INFO - Executing <Task(HttpSensor): is_api_available> on 2023-03-29 18:44:00.987028+00:00
[2023-03-29T18:44:03.137+0000] {standard_task_runner.py:55} INFO - Started process 17273 to run task
[2023-03-29T18:44:03.140+0000] {standard_task_runner.py:82} INFO - Running: ['***', 'tasks', 'run', 'user_processing', 'is_api_available', 'manual__2023-03-29T18:44:00.987028+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/user_processing.py', '--cfg-path', '/tmp/tmpxfk1mktu']
[2023-03-29T18:44:03.142+0000] {standard_task_runner.py:83} INFO - Job 14: Subtask is_api_available
[2023-03-29T18:44:03.187+0000] {task_command.py:376} INFO - Running <TaskInstance: user_processing.is_api_available manual__2023-03-29T18:44:00.987028+00:00 [running]> on host 9dcb783b1f3a
[2023-03-29T18:44:03.227+0000] {taskinstance.py:1592} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=user_processing
AIRFLOW_CTX_TASK_ID=is_api_available
AIRFLOW_CTX_EXECUTION_DATE=2023-03-29T18:44:00.987028+00:00
AIRFLOW_CTX_TRY_NUMBER=1
AIRFLOW_CTX_DAG_RUN_ID=manual__2023-03-29T18:44:00.987028+00:00
[2023-03-29T18:44:03.229+0000] {http.py:120} INFO - Poking: api/
[2023-03-29T18:44:03.237+0000] {base.py:71} INFO - Using connection ID 'user_api' for task execution.
[2023-03-29T18:44:03.239+0000] {http.py:148} INFO - Sending 'GET' to url: https://randomuser.me/api/
[2023-03-29T18:44:03.468+0000] {base.py:213} INFO - Success criteria met. Exiting.
[2023-03-29T18:44:03.483+0000] {taskinstance.py:1406} INFO - Marking task as SUCCESS. dag_id=user_processing, task_id=is_api_available, execution_date=20230329T184400, start_date=20230329T184403, end_date=20230329T184403
[2023-03-29T18:44:03.528+0000] {local_task_job.py:164} INFO - Task exited with return code 0
[2023-03-29T18:44:03.553+0000] {local_task_job.py:273} INFO - 1 downstream tasks scheduled from follow-on schedule check
